config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'

  authenticate :user do
    resources :wines
    resources :strains
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/oenologist.rb
class Oenologist < ApplicationRecord
  has_many :wines_oenologists
  has_many :wines, through: :wines_oenologists
end

app/models/strain.rb
class Strain < ApplicationRecord
    validates :name, presence: :true
    has_many :wines_strains
    has_many :wines, through: :wines_strains
    validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wine.rb
class Wine < ApplicationRecord
  validates :name, presence: :true
  has_many :wines_strains
  has_many :strains, through: :wines_strains, dependent: :destroy
  accepts_nested_attributes_for :wines_strains, allow_destroy: true

  has_many :wines_oenologists
  has_many :oenologist, through: :wines_oenologists, dependent: :destroy
  accepts_nested_attributes_for :wines_oenologists, allow_destroy: true
end

app/models/wines_oenologist.rb
class WinesOenologist < ApplicationRecord
  belongs_to :wine
  belongs_to :oenologist
  accepts_nested_attributes_for :oenologist, allow_destroy: true
end

app/models/wines_strain.rb
class WinesStrain < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
  accepts_nested_attributes_for :strain, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authorize_taster!
    unless current_user.taster?
      flash[:alert]= 'Debes ser catador para poder realizar esta acción'
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @wines = Wine.includes(:wines_strains)
  end
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  before_action :authorize_taster!
  before_action :set_strain, only: %i[ show edit update destroy ]

  # GET /strains or /strains.json
  def index
    @strains = Strain.all
  end

  # GET /strains/1 or /strains/1.json
  def show
  end

  # GET /strains/new
  def new
    @strain = Strain.new
  end

  # GET /strains/1/edit
  def edit
  end

  # POST /strains or /strains.json
  def create
    @strain = Strain.new(strain_params)

    respond_to do |format|
      if @strain.save
        format.html { redirect_to @strain, notice: "Strain was successfully created." }
        format.json { render :show, status: :created, location: @strain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strains/1 or /strains/1.json
  def update
    respond_to do |format|
      if @strain.update(strain_params)
        format.html { redirect_to @strain, notice: "Strain was successfully updated." }
        format.json { render :show, status: :ok, location: @strain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strains/1 or /strains/1.json
  def destroy
    @strain.destroy
    respond_to do |format|
      format.html { redirect_to strains_url, notice: "Strain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strain
      @strain = Strain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def strain_params
      params.require(:strain).permit(:name)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authorize_taster!
  before_action :set_wine, only: %i[ show edit update destroy ]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    # @strains = Strain.all
  end

  # GET /wines/1/edit
  def edit
    @strains = Strain.all
    @wines = Wine.all
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    # byebug
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, wines_strains_attributes: [:id, :strain_id, :porcentage, :_destroy], wines_oenologists_attributes: [:id, :oenologist_id, :note, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
  # se crea método para hacer el select de las cepas, en orden asc
  def strains_for_select
    Strain.order(:name).collect { |g| [g.name, g.id] }
  end
  
  def oenologist_for_select
    Oenologist.order(:name).collect { |g| [g.name, g.id] }
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cepas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
<div class="container text-decoration-none">
	<table class="table">
		<thead>
			<tr>
				<th>Nombre</th>
				<th>Cepas</th>
				<th>Oenologist</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @wines.each do |wine| %>
				<tr>
					<td> <%= wine.name %> </td>
					<td><% wine.wines_strains.each_with_index do |wine_strain, index| %>
						<ul>
							<li> <%= "Cepa #{index + 1}: #{wine_strain.strain.name} | #{wine_strain.porcentage.to_i}%" %>
						</ul>
						<% end %>
					</td>
					<td><% wine.wines_oenologists.each_with_index do |wines_oenologists, index| %>
						<ul>
							<li> <%= "#{wines_oenologists.oenologist.name} | #{wines_oenologists.note}" %>
						</ul>
						<% end %>
					</td>
					<td class="text-center">
					<% if user_signed_in? && current_user.taster? %>
						<%= link_to wine do %>
						<svg aria-hidden="true" focusable="false" data-prefix="far" data-icon="eye" class="svg-inline--fa fa-eye fa-w-18" width="20" height="20" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path fill="currentColor" d="M288 144a110.94 110.94 0 0 0-31.24 5 55.4 55.4 0 0 1 7.24 27 56 56 0 0 1-56 56 55.4 55.4 0 0 1-27-7.24A111.71 111.71 0 1 0 288 144zm284.52 97.4C518.29 135.59 410.93 64 288 64S57.68 135.64 3.48 241.41a32.35 32.35 0 0 0 0 29.19C57.71 376.41 165.07 448 288 448s230.32-71.64 284.52-177.41a32.35 32.35 0 0 0 0-29.19zM288 400c-98.65 0-189.09-55-237.93-144C98.91 167 189.34 112 288 112s189.09 55 237.93 144C477.1 345 386.66 400 288 400z"></path></svg>
						<% end %>
						</td>
						<td class="text-center"> <%= link_to 'Editar', edit_wine_path(wine) %> </td>
						<td class="text-center"> <%= link_to 'Eliminar', wine, method: :delete, data: { confirm: "\n¿Estás seguro?" } %> </td>
					<% end %>
				</tr>
			<% end %>
		<tbody>
	</table>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">
  <%= link_to "Inicio", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Vinos", wines_path, class:"nav-link" %>
      </li>
      <li class="nav-item active">
        <%= link_to "Cepas", strains_path, class:"nav-link" %>
      </li>
    </ul>
    <span class="custom-info">
      <% if user_signed_in? %>
        <%= "| #{current_user.email} |" if user_signed_in? %>
        <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Iniciar sesión", new_user_session_path %>
      <% end %>
    </span>
  </div>
</nav>

app/views/strains/_form.html.erb
<%= form_with(model: strain, local: true) do |form| %>
  <% if strain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(strain.errors.count, "error") %> prohibited this strain from being saved:</h2>

      <ul>
      <% strain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/strains/edit.html.erb
<h1>Editing Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Show', @strain %> |
<%= link_to 'Back', strains_path %>

app/views/strains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Strains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strains.each do |strain| %>
      <tr>
        <td><%= strain.name %></td>
        <td><%= link_to 'Ver', strain %></td>
        <td><%= link_to 'Editar', edit_strain_path(strain) %></td>
        <td><%= link_to 'Eliminar', strain, method: :delete, data: { confirm: '¿Está seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Strain', new_strain_path %>

app/views/strains/new.html.erb
<h1>New Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Back', strains_path %>

app/views/strains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @strain.name %>
</p>

<%= link_to 'Edit', edit_strain_path(@strain) %> |
<%= link_to 'Back', strains_path %>

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Vino" %>
    <%= form.text_field :name, class:"form-control mr-sm-3" %>
  </div>

  <div id="wine_strains" class="form-group">
    <div class="links form-inline">
      <%= link_to_add_association 'Agregar cepa', form, :wines_strains %>
    </div>
  </div>

  <div id="wines_oenologists" class="form-group">
    <div class="links form-inline">
      <%= link_to_add_association 'Agregar nota', form, :wines_oenologists %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_wines_oenologist_fields.html.erb
<div class="nested-fields form-inline">
  <%= f.select :oenologist_id, oenologist_for_select, {}, class:"custom-select mx-sm-3 m-2" %>
  <div class="form-group mr-sm-3 m-2">
    <%= f.label :note %>
    <%= f.number_field :note, class:"form-control mr-sm-3", min:"1", max:"100"%>
  </div>
  <%= link_to_remove_association "Eliminar nota", f %>
</div>

app/views/wines/_wines_strain_fields.html.erb
<div class="nested-fields form-inline">
  <%= f.select :strain_id, strains_for_select, {}, class:"custom-select mx-sm-3 m-2" %>
  <div class="form-group mr-sm-3 m-2">
    <%= f.label :porcentage, "%" %>
    <%= f.number_field :porcentage, class:"form-control mr-sm-3", max:"100" %>
  </div>
  <%= link_to_remove_association "Eliminar cepa", f %>
</div>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<div class="container">
  <%= render 'form', wine: @wine %>

  <% @wines.each do |wine| %>
    <% wine.wines_strains.each_with_index do |wine_strain, index| %>
      <ul>
        <li> <%= "Cepa #{index + 1}: #{wine_strain.strain.name} | #{wine_strain.porcentage.to_i}%" %>
      </ul>
    <% end %>
  <% end %>
</div>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', root_path %>